remote_theme: WildCodeSchool/workshops-jekyll-theme

style: dev
type: workshop
lang: fr
show_clone: "false"
show_toc: "true"
title: "RÃ©ussir votre entretien en algorithme"
description: "un (bon) algo vaut mieux que deux, tu l'auras !"
